import { FileWarning, Fingerprint, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Attachment = { filename: string; attachmentHash: string; size: number; attachmentVerdict: string; isDangerous: boolean; isDoubleExtension: boolean; isMimeMismatch: boolean; vtVerdict: string | null; vtDetectionRatio: number | null };

function parseAttachments(value: string | null | undefined): Attachment[] { try { const parsed = JSON.parse(value || "[]"); return Array.isArray(parsed) ? parsed : []; } catch { return []; } }

export function ForensicExtensions({ investigationId, attachmentAnalysisJson }: { investigationId: number; attachmentAnalysisJson: string | null | undefined }) {
  const utils = trpc.useUtils();
  const chain = trpc.analysis.verifyEvidenceChain.useQuery({ investigationId });
  const enrichAttachment = trpc.analysis.enrichAttachmentVirusTotal.useMutation({ onSuccess: () => { void utils.analysis.detail.invalidate({ investigationId }); toast.success("VirusTotal attachment-hash result saved to this case."); }, onError: (error) => toast.error(error.message) });
  const attachments = parseAttachments(attachmentAnalysisJson);
  return <section className="workbench-evidence-grid forensic-extensions"><article className="panel"><div className="panel-header"><div><span>ATTACHMENT RISK</span><h2>Safe local analysis</h2></div><FileWarning size={18} /></div>{attachments.length ? <div className="attachment-risk-list">{attachments.map((attachment) => <article key={attachment.attachmentHash}><span className={`attachment-verdict attachment-verdict--${attachment.attachmentVerdict.toLowerCase()}`}>{attachment.attachmentVerdict.replace(/_/g, " ")}</span><div><strong>{attachment.filename}</strong><p>{attachment.isDangerous ? "Dangerous extension" : attachment.isDoubleExtension ? "Double extension" : attachment.isMimeMismatch ? "MIME mismatch" : "No local high-risk signal"} · {attachment.size} bytes</p><small>{attachment.attachmentHash}</small>{attachment.vtVerdict ? <em>VirusTotal: {attachment.vtVerdict}{attachment.vtDetectionRatio !== null ? ` · ${Math.round(attachment.vtDetectionRatio * 100)}% malicious ratio` : ""}</em> : <button className="outline-cta" onClick={() => enrichAttachment.mutate({ investigationId, attachmentHash: attachment.attachmentHash })} disabled={enrichAttachment.isPending}>Approve VirusTotal hash check</button>}</div></article>)}</div> : <div className="empty-data empty-data--compact"><span className="empty-data__icon"><FileWarning size={17} /></span><div><strong>No attachment metadata</strong><p>This email did not expose an attachment record for local analysis.</p></div></div>}</article><article className="panel"><div className="panel-header"><div><span>TAMPER-EVIDENT RECORD</span><h2>Evidence chain</h2></div><Fingerprint size={18} /></div><div className="chain-status"><ShieldCheck size={20} /><div><strong>{chain.isLoading ? "Checking evidence records…" : chain.data?.valid ? "Evidence records are consistent" : "Evidence record needs review"}</strong><p>{chain.data ? `${chain.data.blocks} case record${chain.data.blocks === 1 ? "" : "s"} verified locally. This is a private sequential hash chain, not a public blockchain.` : "The chain is checked against this analyst’s private sequence."}</p><small>{chain.data?.latestRoot ? `Latest record root: ${chain.data.latestRoot}` : "No evidence record is available yet."}</small></div></div></article></section>;
}
